app/src/main/java/bg/zahov/app/ui/exercise/ExerciseAdapter.kt
app/src/main/java/bg/zahov/app/ui/exercise/filter/FilterAdapter.kt
app/src/main/java/bg/zahov/app/ui/history/HistoryAdapter.kt
app/src/main/java/bg/zahov/app/ui/measures/MeasurementsAdapter.kt
app/src/main/java/bg/zahov/app/ui/workout/add/ExerciseSetAdapter.kt
app/src/main/java/bg/zahov/app/ui/workout/start/TemplateWorkoutAdapter.kt

- replaced in all old adapters the usage of bindingAdapterPosition with adapterPosition

Adapter position

---

app/src/main/java/bg/zahov/app/ui/measures/info/MeasurementInfoViewModel.kt

Removed forgotten enum.fromKey from measurement info view model

Fix from key measurement info

---

app/src/main/java/bg/zahov/app/ui/workout/WorkoutEnums.kt
app/src/main/java/bg/zahov/app/ui/workout/WorkoutScreen.kt
app/src/main/res/values/strings.xml

Just the ui part of the new workout screen
Before:
After:

Workout screen UI

---

app/src/main/java/bg/zahov/app/ui/workout/start/StartWorkoutScreen.kt

fixed the coloring issues that were introduced when the theme was imported
Before:
After:

fixed colors after the new color theme

---

app/build.gradle.kts

Adding imports for compose ui testing

Gradle import test

---

app/src/main/java/bg/zahov/app/ui/workout/WorkoutScreen.kt

- Removed redeclaration of workout entry in workout screen

removed redeclaration of workout entry

---

app/src/main/java/bg/zahov/app/ui/workout/WorkoutViewModelNew.kt

- removed unnecessary for loop with .map 
- updated List of exercises to linkedMap of exercise.name and exercise in ExerciseSummary
- updated kdoc

Workout view model

---

app/src/main/java/bg/zahov/app/ui/history/HistoryScreen.kt

fixed colors accordingly after the color theme change

---

app/build.gradle.kts

Reverts HauntedMilkshake/fitness_app#62

Revert "upgraded target sdk"

---

app/src/main/java/bg/zahov/app/MyApplication.kt
app/src/main/java/bg/zahov/app/data/interfaces/ExercisesTopBarHandler.kt
app/src/main/java/bg/zahov/app/data/provider/ExercisesTopBarManager.kt
app/src/main/java/bg/zahov/app/ui/exercise/topbar/ExercisesTopBar.kt
app/src/main/java/bg/zahov/app/ui/exercise/topbar/ExercisesTopBarViewModel.kt
app/src/main/res/values/strings.xml

Added special top bar for Exercises screen
It removes dropdown bugs from the old one + its scaffold ready.
Its not attach  ( waiting for the scaffold changes )
Old:
New:

added functional top app bar for exercises screen

---

app/src/main/java/bg/zahov/app/ui/BottomBar.kt

Added bottom bar for #68 
Old:
New:

Bottom bar

---

app/build.gradle.kts
app/src/main/java/bg/zahov/app/MainActivity.kt
app/src/main/java/bg/zahov/app/MyApplication.kt
build.gradle.kts
gradle/libs.versions.toml

`https://trello.com/c/6be8HzsT/58-1-add-hilt-to-the-application`
Added Hilt to the project

Added hilt dependencies

---

app/src/main/java/bg/zahov/app/ui/authentication/signup/SignupScreen.kt
app/src/main/java/bg/zahov/app/ui/authentication/signup/SignupViewModel.kt

Tested manually. Followed the guide -> [https://trello.com/c/933QXRe0/60-5-add-hilt-into-viewmodels](url)

Migrated signup view model to hilt

---

app/src/main/java/bg/zahov/app/ui/exercise/add/AddExerciseScreen.kt
app/src/main/java/bg/zahov/app/ui/exercise/add/AddExerciseViewModel.kt

Tested manually. Followed the guide -> [https://trello.com/c/933QXRe0/60-5-add-hilt-into-viewmodels](https://github.com/HauntedMilkshake/fitness_app/pull/url)

AddExerciseViewModel to HiltViewModel

---

app/src/main/java/bg/zahov/app/data/provider/FilterProvider.kt
app/src/main/java/bg/zahov/app/ui/exercise/filter/FilterDialog.kt
app/src/main/java/bg/zahov/app/ui/exercise/filter/FilterViewModel.kt

Migrated filter vm to be a hilt vm. 

Hilt filter vm

---

app/src/main/java/bg/zahov/app/ui/error/ShuttingDownScreen.kt
app/src/main/java/bg/zahov/app/ui/error/ShuttingDownViewModel.kt

This is no longer used for obvious reasons however I felt sympathy for it

Doomsday clock to hilt vm

---

app/src/main/java/bg/zahov/app/ui/exercise/info/ExerciseInfoScreen.kt
app/src/main/java/bg/zahov/app/ui/exercise/info/ExerciseInfoViewModel.kt

Migrated the view model to a hilt view model

Exercise info vm to hilt vm

---

app/src/main/java/bg/zahov/app/ui/exercise/info/ExerciseInfoScreen.kt
app/src/main/java/bg/zahov/app/ui/exercise/info/ExerciseInfoViewModel.kt
app/src/main/java/bg/zahov/app/ui/exercise/topbar/TopBarExercise.kt
app/src/main/java/bg/zahov/app/ui/exercise/topbar/TopBarExerciseViewModel.kt

Migrated  top bar exercise to be a hilt view model.

Hilt top bar exercise vm

---

app/src/main/java/bg/zahov/app/ui/history/calendar/CalendarScreen.kt
app/src/main/java/bg/zahov/app/ui/history/calendar/CalendarViewModel.kt

Migrated calendar view model to be a hilt view model.
Manually tested

Migrate calendar vm to hilt vm

---

app/src/main/java/bg/zahov/app/ui/history/HistoryScreen.kt
app/src/main/java/bg/zahov/app/ui/history/HistoryViewModel.kt

Migrated history vm to hilt vm.

Migrated history vm to hilt vm

---

app/src/main/java/bg/zahov/app/ui/home/HomeScreen.kt
app/src/main/java/bg/zahov/app/ui/home/HomeViewModel.kt

Migrated home vm to hilt vm
Manually tested

Migrated home vm to hilt vm

---

app/src/main/java/bg/zahov/app/ui/measures/info/MeasurementInfoScreen.kt
app/src/main/java/bg/zahov/app/ui/measures/info/MeasurementInfoViewModel.kt

Migrate measurement info vm to hilt
(Service error handler was no longer used so I remove it)

Migrate measurement info vm to hilt

---

app/src/main/java/bg/zahov/app/ui/workout/WorkoutScreen.kt
app/src/main/java/bg/zahov/app/ui/workout/add/AddTemplateWorkoutViewModel.kt

IMPORTANT
Currently the screen doesn't work as intended. I have added a card to trello
Migrate add template workout vm to hilt
Removed toast manager because currently it doesn't work with hilt ( we will remove toast manager and switch to snackbar )

Migrate add template workout vm to hilt

---

app/src/main/java/bg/zahov/app/ui/settings/SettingsScreen.kt
app/src/main/java/bg/zahov/app/ui/settings/SettingsViewModel.kt

Migrate Edit profile vm to hilt

Migrate settings vm to hilt

---

app/src/main/java/bg/zahov/app/LoadingViewModel.kt
app/src/main/java/bg/zahov/app/MainNavGraph.kt

Change loading view model to be using hilt

Loading view model with hilt

---

app/src/main/java/bg/zahov/app/ui/workout/finish/WorkoutFinishScreen.kt
app/src/main/java/bg/zahov/app/ui/workout/finish/WorkoutFinishViewModel.kt

Migrate workout finish vm to hilt

Migrate workout finish vm to hilt

---

app/src/main/java/bg/zahov/app/data/di/ApplicationModule.kt
app/src/main/java/bg/zahov/app/data/provider/WorkoutStateManager.kt
app/src/main/java/bg/zahov/app/ui/workout/WorkoutScreen.kt
app/src/main/java/bg/zahov/app/ui/workout/WorkoutViewModel.kt

Migrate workout vm to hilt
Removed toast manager because currently it doesn't work with hilt ( we will remove toast manager and switch to snackbar )

Migrate workout vm to hilt

---

app/src/main/java/bg/zahov/app/App.kt
app/src/main/java/bg/zahov/app/WorkoutManagerViewModel.kt
app/src/main/java/bg/zahov/app/data/provider/WorkoutStateManager.kt
app/src/main/java/bg/zahov/app/ui/workout/start/StartWorkoutScreen.kt
app/src/main/java/bg/zahov/app/ui/workout/start/StartWorkoutViewModel.kt

IMPORTANT
This screen is dependent on changes from the other prs
Once the other "vm to hilt" prs are merged , this screen should be tested 
Migrate start workout vm to hilt
Removed toast manager because currently it doesn't work with hilt ( we will remove toast manager and switch to snackbar )

Migrate start workout vm to hilt [DON'T MERGE]

---

app/src/main/java/bg/zahov/app/data/di/ProviderModule.kt
app/src/main/java/bg/zahov/app/data/repository/AuthenticationImpl.kt
app/src/main/java/bg/zahov/app/data/repository/UserRepositoryImpl.kt
app/src/main/java/bg/zahov/app/data/repository/WorkoutRepositoryImpl.kt

For providing our providers with their repositories through their constructors. -> [https://trello.com/c/V89Ng77w/90-add-module-for-the-provider-layer-of-the-application](url)
There weren't any build issues and I tested the app manually.

Provider module
